

# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/beats/filebeat:6.5.1
RUN filebeat -e -strict.perms=false

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
